name: Example Workflow
'on':
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: World
        type: string
jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest
   
